package eggshooter;


import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JButton;


/**
 *
 * @author Group Javascript Leader: Nguyen Vuong Khang Hy Tester: Nguyen Minh
 * Long Designer: Nguyen Tan Vu Class IA1401 Game Egg Shooter
 */
public class frmMenu extends javax.swing.JFrame {
    
    private String supermode;
    private int demo = 0;
    private boolean isPress = true;
    /**
     * Creates new form Home
     */
    public frmMenu() {
        initComponents();
        this.setLocationRelativeTo(null); // centering the frame
        this.setIconImage(new ImageIcon("src/img/EggShooter.png").getImage());
        pnlArcadeMenu.setVisible(false);
        btnSlow.setVisible(false);
        btnFast.setVisible(false);
        btnDangerous.setVisible(false);
        btnBack.setVisible(false);
        btnBack1.setVisible(false);
        txtUser.setVisible(false);
        lblName.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlMainMenu = new javax.swing.JPanel();
        btnArcade = new javax.swing.JButton();
        btnTimeRush = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        lblBGMainMenu = new javax.swing.JLabel();
        pnlArcadeMenu = new javax.swing.JPanel();
        btnSlow = new javax.swing.JButton();
        btnFast = new javax.swing.JButton();
        btnDangerous = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblBGArcadeMenu = new javax.swing.JLabel();
        pnlUser = new javax.swing.JPanel();
        txtUser = new javax.swing.JTextField();
        lblPlay = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblbgUser = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();
        lblBGArcadeMenu1 = new javax.swing.JLabel();
        lblBGUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Egg Shooter");
        setName("frmHome"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMainMenu.setPreferredSize(new java.awt.Dimension(338, 710));
        pnlMainMenu.setLayout(null);

        btnArcade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnArcade.png"))); // NOI18N
        btnArcade.setBorder(null);
        btnArcade.setBorderPainted(false);
        btnArcade.setContentAreaFilled(false);
        btnArcade.setFocusPainted(false);
        btnArcade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnArcadeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnArcadeMouseExited(evt);
            }
        });
        btnArcade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArcadeActionPerformed(evt);
            }
        });
        pnlMainMenu.add(btnArcade);
        btnArcade.setBounds(40, 290, 250, 64);

        btnTimeRush.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnTimeRush.png"))); // NOI18N
        btnTimeRush.setBorder(null);
        btnTimeRush.setBorderPainted(false);
        btnTimeRush.setContentAreaFilled(false);
        btnTimeRush.setFocusPainted(false);
        btnTimeRush.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTimeRushMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTimeRushMouseExited(evt);
            }
        });
        btnTimeRush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimeRushActionPerformed(evt);
            }
        });
        pnlMainMenu.add(btnTimeRush);
        btnTimeRush.setBounds(40, 380, 249, 66);

        btnHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/help.png"))); // NOI18N
        btnHelp.setBorder(null);
        btnHelp.setBorderPainted(false);
        btnHelp.setContentAreaFilled(false);
        btnHelp.setFocusPainted(false);
        btnHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHelpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHelpMouseExited(evt);
            }
        });
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        pnlMainMenu.add(btnHelp);
        btnHelp.setBounds(70, 490, 74, 52);

        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/about.png"))); // NOI18N
        btnAbout.setBorder(null);
        btnAbout.setBorderPainted(false);
        btnAbout.setContentAreaFilled(false);
        btnAbout.setFocusPainted(false);
        btnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAboutMouseExited(evt);
            }
        });
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });
        pnlMainMenu.add(btnAbout);
        btnAbout.setBounds(180, 490, 74, 52);

        lblBGMainMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Home.png"))); // NOI18N
        lblBGMainMenu.setMaximumSize(new java.awt.Dimension(338, 710));
        lblBGMainMenu.setMinimumSize(new java.awt.Dimension(338, 710));
        lblBGMainMenu.setPreferredSize(new java.awt.Dimension(338, 710));
        pnlMainMenu.add(lblBGMainMenu);
        lblBGMainMenu.setBounds(0, 0, 338, 710);

        getContentPane().add(pnlMainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 338, 710));

        pnlArcadeMenu.setPreferredSize(new java.awt.Dimension(338, 710));
        pnlArcadeMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSlow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnSlow.png"))); // NOI18N
        btnSlow.setBorder(null);
        btnSlow.setBorderPainted(false);
        btnSlow.setContentAreaFilled(false);
        btnSlow.setFocusPainted(false);
        btnSlow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSlowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSlowMouseExited(evt);
            }
        });
        btnSlow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlowActionPerformed(evt);
            }
        });
        pnlArcadeMenu.add(btnSlow, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 250, 160, 42));

        btnFast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnFast.png"))); // NOI18N
        btnFast.setBorder(null);
        btnFast.setBorderPainted(false);
        btnFast.setContentAreaFilled(false);
        btnFast.setFocusPainted(false);
        btnFast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFastMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFastMouseExited(evt);
            }
        });
        btnFast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFastActionPerformed(evt);
            }
        });
        pnlArcadeMenu.add(btnFast, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 310, 160, 42));

        btnDangerous.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnDangerous.png"))); // NOI18N
        btnDangerous.setBorder(null);
        btnDangerous.setBorderPainted(false);
        btnDangerous.setContentAreaFilled(false);
        btnDangerous.setFocusPainted(false);
        btnDangerous.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDangerousMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDangerousMouseExited(evt);
            }
        });
        btnDangerous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangerousActionPerformed(evt);
            }
        });
        pnlArcadeMenu.add(btnDangerous, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 370, 160, 42));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnBack.png"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.setFocusPainted(false);
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        pnlArcadeMenu.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 480, 160, 42));

        lblBGArcadeMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bgArcadeMenu.png"))); // NOI18N
        lblBGArcadeMenu.setPreferredSize(new java.awt.Dimension(338, 710));
        pnlArcadeMenu.add(lblBGArcadeMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 338, 710));

        getContentPane().add(pnlArcadeMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 338, 710));

        pnlUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUserMousePressed(evt);
            }
        });
        pnlUser.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 240, 180, 30));

        lblPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnPlay.png"))); // NOI18N
        lblPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPlayMouseClicked(evt);
            }
        });
        pnlUser.add(lblPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 280, -1, -1));

        lblName.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 0, 0));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlUser.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 222, 182));

        lblbgUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/EnterUserBoard.png"))); // NOI18N
        pnlUser.add(lblbgUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 160, -1, -1));

        btnBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnBack.png"))); // NOI18N
        btnBack1.setBorder(null);
        btnBack1.setBorderPainted(false);
        btnBack1.setContentAreaFilled(false);
        btnBack1.setFocusPainted(false);
        btnBack1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBack1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBack1MouseExited(evt);
            }
        });
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        pnlUser.add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 370, 160, 42));

        lblBGArcadeMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bgEnterUser.png"))); // NOI18N
        lblBGArcadeMenu1.setPreferredSize(new java.awt.Dimension(338, 710));
        pnlUser.add(lblBGArcadeMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 338, 710));

        lblBGUser.setOpaque(true);
        lblBGUser.setPreferredSize(new java.awt.Dimension(338, 710));
        pnlUser.add(lblBGUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 338, 710));

        getContentPane().add(pnlUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 338, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Display frame frmGuide
     *
     * @param evt
     */
    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        frmGuide g = new frmGuide();
        g.setVisible(true);
    }//GEN-LAST:event_btnHelpActionPerformed
    /**
     * Display frame frmAbout
     *
     * @param evt
     */
    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        frmAbout a = new frmAbout();
        a.setVisible(true);
    }//GEN-LAST:event_btnAboutActionPerformed
    /**
     * Change icon button
     *
     * @param evt
     */
    private void btnArcadeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArcadeMouseEntered
        btnArcade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnArcade1.png")));
    }//GEN-LAST:event_btnArcadeMouseEntered
    /**
     * Change icon button
     *
     * @param evt
     */
    private void btnArcadeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArcadeMouseExited
        btnArcade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnArcade.png")));
    }//GEN-LAST:event_btnArcadeMouseExited
    /**
     * Change icon button
     *
     * @param evt
     */
    private void btnTimeRushMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimeRushMouseEntered
        btnTimeRush.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnTimeRush1.png")));
    }//GEN-LAST:event_btnTimeRushMouseEntered
    /**
     * Change icon button
     *
     * @param evt
     */
    private void btnTimeRushMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimeRushMouseExited
        btnTimeRush.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnTimeRush.png")));
    }//GEN-LAST:event_btnTimeRushMouseExited
    /**
     * Change icon button
     *
     * @param evt
     */
    private void btnHelpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHelpMouseEntered
        btnHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/help1.png")));
    }//GEN-LAST:event_btnHelpMouseEntered
    /**
     * Change icon button
     *
     * @param evt
     */
    private void btnHelpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHelpMouseExited
        btnHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/help.png")));
    }//GEN-LAST:event_btnHelpMouseExited
    /**
     * Change icon button
     *
     * @param evt
     */
    private void btnAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseEntered
        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/about1.png")));
    }//GEN-LAST:event_btnAboutMouseEntered
    /**
     * Change icon button
     *
     * @param evt
     */
    private void btnAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseExited
        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/about.png")));
    }//GEN-LAST:event_btnAboutMouseExited
    /**
     * Show panel pnlArcadeMenu
     *
     * @param evt
     */
    private void btnArcadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArcadeActionPerformed
        pnlMainMenu.setVisible(false);
        pnlArcadeMenu.setVisible(true);
        btnSlow.setVisible(true);
        btnFast.setVisible(true);
        btnDangerous.setVisible(true);
        btnBack.setVisible(true);
    }//GEN-LAST:event_btnArcadeActionPerformed
    /**
     * Display frame frmBoard and play game on mode Time Rush
     *
     * @param evt
     */
    private void btnTimeRushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimeRushActionPerformed
        supermode = "timerush";
        initEnterUser();
    }//GEN-LAST:event_btnTimeRushActionPerformed
    /**
     * Change icon button
     *
     * @param evt
     */
    private void btnSlowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSlowMouseEntered
        btnSlow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnSlow1.png")));
    }//GEN-LAST:event_btnSlowMouseEntered
    /**
     * Change icon button
     *
     * @param evt
     */
    private void btnSlowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSlowMouseExited
        btnSlow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnSlow.png")));
    }//GEN-LAST:event_btnSlowMouseExited
    /**
     * Change icon button
     *
     * @param evt
     */
    private void btnFastMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFastMouseEntered
        btnFast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnFast1.png")));
    }//GEN-LAST:event_btnFastMouseEntered
    /**
     * Change icon button
     *
     * @param evt
     */
    private void btnFastMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFastMouseExited
        btnFast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnFast.png")));
    }//GEN-LAST:event_btnFastMouseExited
    /**
     * Change icon button
     *
     * @param evt
     */
    private void btnDangerousMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangerousMouseEntered
        btnDangerous.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnDangerous1.png")));
    }//GEN-LAST:event_btnDangerousMouseEntered
    /**
     * Change icon button
     *
     * @param evt
     */
    private void btnDangerousMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangerousMouseExited
        btnDangerous.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnDangerous.png")));
    }//GEN-LAST:event_btnDangerousMouseExited
    /**
     * Change icon button
     *
     * @param evt
     */
    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnBack1.png")));
    }//GEN-LAST:event_btnBackMouseEntered
    /**
     * Change icon button
     *
     * @param evt
     */
    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnBack.png")));
    }//GEN-LAST:event_btnBackMouseExited
    /**
     * Display frame frmBoard and play game on mode Arcade-Slow
     *
     * @param evt
     */
    private void btnSlowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlowActionPerformed
        supermode = "slow";
        initEnterUser();
    }//GEN-LAST:event_btnSlowActionPerformed
    /**
     * Display frame frmBoard and play game on mode Arcade-Fast
     *
     * @param evt
     */
    private void btnFastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFastActionPerformed
        supermode = "fast";
        initEnterUser();
    }//GEN-LAST:event_btnFastActionPerformed
    /**
     * Display frame frmBoard and play game on mode Arcade-Dangerous
     *
     * @param evt
     */
    private void btnDangerousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangerousActionPerformed
        supermode = "dangerous";
        initEnterUser();
    }//GEN-LAST:event_btnDangerousActionPerformed
    /**
     * Back to main menu
     *
     * @param evt
     */
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        pnlArcadeMenu.setVisible(false);
        pnlMainMenu.setVisible(true);
        btnSlow.setVisible(false);
        btnFast.setVisible(false);
        btnDangerous.setVisible(false);
        btnBack.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBack1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack1MouseEntered
        btnBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnBack1.png")));
    }//GEN-LAST:event_btnBack1MouseEntered

    private void btnBack1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack1MouseExited
        btnBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnBack.png")));
    }//GEN-LAST:event_btnBack1MouseExited

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        pnlUser.setVisible(false);
        pnlMainMenu.setVisible(true);
        btnSlow.setVisible(false);
        btnFast.setVisible(false);
        btnDangerous.setVisible(false);
        btnBack.setVisible(false);
    }//GEN-LAST:event_btnBack1ActionPerformed
    /**
     * User input username to play this game
     * @param evt 
     */
    private void lblPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPlayMouseClicked
        //check username cannot be empty or exceed 50 characters
        if(txtUser.getText().equals("") || txtUser.getText().length()>50  ){
            //show red notification
            txtUser.setText("Invalid username!");
            txtUser.setForeground(Color.red);
            demo=1;
            isPress=false;
        }else if(isPress==true){        
            demo=0;
            enterUserBoard(supermode);
        }            
    }//GEN-LAST:event_lblPlayMouseClicked
    /**
     * User retype username and remove red message
     * @param evt 
     */
    private void txtUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMousePressed
        if(demo==1){            
            txtUser.setText("");
            txtUser.setForeground(Color.black);
            demo=0;
            isPress=true;
        }      
    }//GEN-LAST:event_txtUserMousePressed
    
    private void initEnterUser() {
        pnlMainMenu.setVisible(false);
        pnlArcadeMenu.setVisible(false);
        pnlUser.setVisible(true);
        btnBack1.setVisible(true);
        txtUser.setVisible(true);
    }
    
    private void enterUserBoard(String supermode) {
        pnlMainMenu.setVisible(true);
        pnlUser.setVisible(false);
        switch (supermode) {
            case "timerush":
                btnTimeRush.setEnabled(false);
                frmBoard timerush = new frmBoard(this, 0, 1, "timerush", txtUser.getText());
                this.setVisible(false);
                timerush.setVisible(true);
                break;
            case "slow":
                frmBoard slow = new frmBoard(this, 0, 0, "slow", txtUser.getText());
                this.setVisible(false);
                slow.setVisible(true);
                break;
            case "fast":
                frmBoard fast = new frmBoard(this, 1, 0, "fast", txtUser.getText());
                this.setVisible(false);
                fast.setVisible(true);
                break;
            case "dangerous":
                frmBoard dangerous = new frmBoard(this, 2, 0, "dangerous", txtUser.getText());
                this.setVisible(false);
                dangerous.setVisible(true);
                break;
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    public JButton getBtnArcade() {
        return btnArcade;
    }

    public void setBtnArcade(JButton btnArcade) {
        this.btnArcade = btnArcade;
    }

    public JButton getBtnTimeRush() {
        return btnTimeRush;
    }

    public void setBtnTimeRush(JButton btnTimeRush) {
        this.btnTimeRush = btnTimeRush;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnArcade;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnDangerous;
    private javax.swing.JButton btnFast;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnSlow;
    private javax.swing.JButton btnTimeRush;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBGArcadeMenu;
    private javax.swing.JLabel lblBGArcadeMenu1;
    private javax.swing.JLabel lblBGMainMenu;
    private javax.swing.JLabel lblBGUser;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPlay;
    private javax.swing.JLabel lblbgUser;
    private javax.swing.JPanel pnlArcadeMenu;
    private javax.swing.JPanel pnlMainMenu;
    private javax.swing.JPanel pnlUser;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
